# Generated by Django 5.2.12 on 2026-03-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='admin',
        ),
    ]
