# Generated by Django 5.2.12 on 2026-03-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_admin_product_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='admin',
        ),
    ]
